import React, { useState } from 'react';
import { Upload, AlertTriangle } from 'lucide-react';

export default function BulkEnrollment() {
  const [file, setFile] = useState<File | null>(null);
  const [progress, setProgress] = useState(0);
  const [results, setResults] = useState<any[]>([]);

  const handleUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setFile(e.target.files[0]);
    }
  };

  const simulateProcess = () => {
    if (!file) return;
    setProgress(10);
    setTimeout(() => setProgress(50), 500);
    setTimeout(() => {
      setProgress(100);
      setResults([
        { student: 'STU001', success: true, message: 'Enrolled successfully' },
        { student: 'STU002', success: false, message: 'Card digest duplicate' },
        { student: 'STU003', success: true, message: 'Enrolled successfully' }
      ]);
    }, 1000);
  };

  return (
    <div className="bg-white p-6 rounded-2xl shadow-sm max-w-3xl mx-auto">
      <h2 className="text-xl font-black mb-4">Bulk Card Enrollment</h2>
      
      <div className="bg-amber-50 p-4 rounded-xl flex gap-3 mb-6 border border-amber-200">
        <AlertTriangle className="text-amber-600 flex-shrink-0" />
        <div className="text-sm text-amber-800">
          <p className="font-bold">Security Warning</p>
          <p>Do not upload CSVs containing raw UIDs. Only upload cryptographically secure card digests generated by an authorized provisioning station.</p>
        </div>
      </div>

      {!results.length ? (
        <div className="space-y-4">
          <div className="border-2 border-dashed border-slate-300 rounded-xl p-10 text-center">
            <Upload className="w-10 h-10 text-slate-400 mx-auto mb-3" />
            <p className="text-sm text-slate-600 font-bold mb-2">Upload Provisioning Data (.json, .csv)</p>
            <input type="file" onChange={handleUpload} className="text-sm" accept=".csv,.json" />
          </div>
          <button 
            onClick={simulateProcess} 
            disabled={!file || progress > 0} 
            className="w-full py-3 bg-blue-600 text-white rounded-xl font-bold disabled:opacity-50"
          >
            {progress > 0 && progress < 100 ? `Processing... ${progress}%` : 'Process Upload'}
          </button>
          
          {progress > 0 && (
            <div className="w-full bg-slate-200 rounded-full h-2.5">
              <div className="bg-blue-600 h-2.5 rounded-full" style={{ width: `${progress}%` }}></div>
            </div>
          )}
        </div>
      ) : (
        <div className="space-y-4">
          <div className="grid grid-cols-3 gap-4 mb-4">
            <div className="bg-slate-50 p-3 rounded-xl text-center"><div className="text-2xl font-black">{results.length}</div><div className="text-xs text-slate-500">Total</div></div>
            <div className="bg-emerald-50 p-3 rounded-xl text-center"><div className="text-2xl font-black text-emerald-700">{results.filter(r => r.success).length}</div><div className="text-xs text-slate-500">Succeeded</div></div>
            <div className="bg-rose-50 p-3 rounded-xl text-center"><div className="text-2xl font-black text-rose-700">{results.filter(r => !r.success).length}</div><div className="text-xs text-slate-500">Failed</div></div>
          </div>
          
          <div className="max-h-64 overflow-auto border rounded-xl">
            <table className="w-full text-sm">
              <thead className="bg-slate-50 sticky top-0">
                <tr className="text-left"><th className="p-2">Student</th><th className="p-2">Result</th><th className="p-2">Message</th></tr>
              </thead>
              <tbody>
                {results.map((r, i) => (
                  <tr key={i} className="border-t">
                    <td className="p-2 font-mono">{r.student}</td>
                    <td className="p-2">
                      <span className={`px-2 py-1 rounded text-xs font-bold ${r.success ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'}`}>
                        {r.success ? 'Success' : 'Failed'}
                      </span>
                    </td>
                    <td className="p-2 text-slate-600">{r.message}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <button onClick={() => { setResults([]); setProgress(0); setFile(null); }} className="px-4 py-2 bg-slate-100 rounded-xl font-bold text-sm">Upload Another</button>
        </div>
      )}
    </div>
  );
}
