apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: school-attendance-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: school-attendance-secret
    creationPolicy: Owner
  data:
    - secretKey: SESSION_SECRET
      remoteRef:
        key: production/school-attendance
        property: SESSION_SECRET
    - secretKey: REDIS_KEY_HMAC_SECRET
      remoteRef:
        key: production/school-attendance
        property: REDIS_KEY_HMAC_SECRET
    - secretKey: METRICS_AUTH_TOKEN
      remoteRef:
        key: production/school-attendance
        property: METRICS_AUTH_TOKEN
    - secretKey: DATABASE_URL
      remoteRef:
        key: production/school-attendance
        property: DATABASE_URL
