apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: school-attendance-web-pdb
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: school-attendance
      component: web
