apiVersion: v1
kind: ServiceAccount
metadata:
  name: school-attendance-web-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: school-attendance-worker-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: school-attendance-migration-sa

