apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: school-attendance-servicemonitor
spec:
  selector:
    matchLabels:
      app: school-attendance-web
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      bearerTokenSecret:
        name: school-attendance-secrets
        key: METRICS_AUTH_TOKEN
