#!/bin/sh
set -eu

until PGPASSWORD="$MIGRATION_DB_PASSWORD" psql "postgresql://${MIGRATION_DB_USER}:${MIGRATION_DB_PASSWORD}@${DB_HOST}:5432/${POSTGRES_DB}" -c 'select 1' >/dev/null 2>&1; do
  sleep 2
done

PGPASSWORD="$MIGRATION_DB_PASSWORD" psql "postgresql://${MIGRATION_DB_USER}:${MIGRATION_DB_PASSWORD}@${DB_HOST}:5432/${POSTGRES_DB}" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${APP_DB_USER}') THEN
    CREATE ROLE "${APP_DB_USER}" LOGIN PASSWORD '${APP_DB_PASSWORD}';
  ELSE
    ALTER ROLE "${APP_DB_USER}" LOGIN PASSWORD '${APP_DB_PASSWORD}';
  END IF;
END
\$\$;
ALTER ROLE "${APP_DB_USER}" NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${SYSTEM_DB_USER}') THEN
    CREATE ROLE "${SYSTEM_DB_USER}" LOGIN PASSWORD '${SYSTEM_DB_PASSWORD}';
  ELSE
    ALTER ROLE "${SYSTEM_DB_USER}" LOGIN PASSWORD '${SYSTEM_DB_PASSWORD}';
  END IF;
END
\$\$;
ALTER ROLE "${SYSTEM_DB_USER}" NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${APP_DB_USER}";
GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${SYSTEM_DB_USER}";
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO "${APP_DB_USER}";
GRANT USAGE ON SCHEMA public TO "${SYSTEM_DB_USER}";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "${APP_DB_USER}";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "${SYSTEM_DB_USER}";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "${APP_DB_USER}";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "${SYSTEM_DB_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${APP_DB_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${SYSTEM_DB_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${APP_DB_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${SYSTEM_DB_USER}";
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${AUTH_DB_USER}') THEN
    CREATE ROLE "${AUTH_DB_USER}" LOGIN PASSWORD '${AUTH_DB_PASSWORD}';
  ELSE
    ALTER ROLE "${AUTH_DB_USER}" LOGIN PASSWORD '${AUTH_DB_PASSWORD}';
  END IF;
END
\$\$;
ALTER ROLE "${AUTH_DB_USER}" NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${AUTH_DB_USER}";
GRANT USAGE ON SCHEMA public TO "${AUTH_DB_USER}";
SQL
