// scripts/gen-env-example.ts
import fs from 'node:fs';
import path from 'node:path';
import { ENV_DOCS } from '../src/env';

export function generateEnvDocs(projectRoot: string = process.cwd()): void {
  const groups = new Map<string, string[]>();

  for (const [key, meta] of Object.entries(ENV_DOCS)) {
    const lines = groups.get(meta.group) ?? [];
    lines.push(`# ${meta.help}${meta.secret ? ' (SECRET — generated by install.sh, never commit)' : ''}`);
    lines.push(`${key}=${meta.secret ? '' : meta.example ?? ''}`, '');
    groups.set(meta.group, lines);
  }

  const outLines: string[] = [
    '# GENERATED by scripts/gen-env-example.ts — edit src/env.ts instead.',
    '',
  ];

  for (const [groupName, lines] of groups.entries()) {
    outLines.push(`# ── ${groupName} ${'─'.repeat(Math.max(0, 56 - groupName.length))}`);
    outLines.push(...lines);
  }

  const envExamplePath = path.resolve(projectRoot, '.env.example');
  fs.writeFileSync(envExamplePath, outLines.join('\n'));

  const today = '2026-10-06';
  const configDocPath = path.resolve(projectRoot, 'docs/reference/configuration.md');
  const docLines: string[] = [
    '---',
    'title: "Configuration Reference"',
    'owner: "@Kh3rwa1"',
    'applies_to: ">=2.0.0"',
    `last_verified: ${today}`,
    '---',
    '',
    '# Configuration Reference',
    '',
    'Environment variables and configuration schema automatically generated from `src/env.ts`.',
    'To update this reference or `.env.example`, edit `src/env.ts` and run `npm run gen:env`.',
    '',
    '| Variable | Group | Description | Secret | Default / Example |',
    '|---|---|---|---|---|',
    ...Object.entries(ENV_DOCS).map(
      ([k, m]) =>
        `| \`${k}\` | ${m.group} | ${m.help} | ${m.secret ? 'yes' : 'no'} | ${
          m.secret ? '*(generated)*' : m.example ? `\`${m.example}\`` : '—'
        } |`
    ),
    '',
  ];

  fs.writeFileSync(configDocPath, docLines.join('\n'));
}

if (process.argv[1]?.endsWith('gen-env-example.ts')) {
  generateEnvDocs();
  console.log('Generated .env.example and docs/reference/configuration.md');
}
